import {
  Monitor,
  Brain,
  Shield,
  Cloud,
  Database,
  Globe,
  Cpu,
  Gamepad2,
  Link,
  Bot,
  ShoppingBag,
  HeartPulse,
  Landmark,
  Factory,
  Film,
  Building2,
  Package,
  FlaskConical,
  Plane,
} from "lucide-react";
import type { Industry } from "@/types";
import type { LucideIcon } from "lucide-react";

export const INDUSTRY_ICONS: Record<Industry, LucideIcon> = {
  "Software & Technology": Monitor,
  "Artificial Intelligence & Machine Learning": Brain,
  "Cybersecurity & Information Security": Shield,
  "Cloud Computing & DevOps": Cloud,
  "Data Engineering & Analytics": Database,
  "Web & Mobile Development": Globe,
  "Embedded Systems & IoT": Cpu,
  "Game Development & XR": Gamepad2,
  "Blockchain & Web3": Link,
  "Robotics & Automation": Bot,
  "Retail & Consumer Commerce": ShoppingBag,
  "Healthcare & Life Sciences": HeartPulse,
  "Financial Services & Banking": Landmark,
  "Engineering & Manufacturing": Factory,
  "Media & Digital Entertainment": Film,
  "Infrastructure & Real Estate": Building2,
  "Consumer Goods & FMCG": Package,
  "Pharmaceuticals & Biotech": FlaskConical,
  "Travel, Hospitality & Tourism": Plane,
};
